python train_model.py m i 0
python train_model.py q i 0
python train_model.py m i 1
python train_model.py q i 1
python train_model.py m i 2
python train_model.py q i 2
python train_model.py m i 3
python train_model.py q i 3
python train_model.py m i 4
python train_model.py q i 4
python train_model.py m i 5
python train_model.py q i 5
python train_model.py m i 6
python train_model.py q i 6
python train_model.py m i 7
python train_model.py q i 7
python train_model.py m i 8
python train_model.py q i 8
python train_model.py m i 9
python train_model.py q i 9
