python infer_sectors.py 1
python infer_sectors.py 2
python infer_sectors.py 3
python infer_sectors.py 4
python infer_sectors.py 5
python infer_sectors.py 6
python infer_sectors.py 7
python infer_sectors.py 8
python infer_sectors.py 9
python infer_sectors.py 10
python infer_sectors.py 11
python infer_sectors.py 12
python infer_sectors.py 13
python infer_sectors.py 14
python infer_sectors.py 15
python infer_sectors.py 16
python infer_sectors.py 17
python infer_sectors.py 18
python infer_sectors.py 19
python infer_sectors.py 20
python infer_sectors.py 21
python infer_sectors.py 22
python infer_sectors.py 23
python infer_sectors.py 24
python infer_sectors.py 25
python infer_sectors.py 26
python infer_sectors.py 27
python infer_sectors.py 28
python infer_sectors.py 29
python infer_sectors.py 30
python infer_sectors.py 31
python infer_sectors.py 32
python infer_sectors.py 33
python infer_sectors.py 34
python infer_sectors.py 35
python infer_sectors.py 36
python infer_sectors.py 37
python infer_sectors.py 38
python infer_sectors.py 39
python infer_sectors.py 40
python infer_sectors.py 41
python infer_sectors.py 42
python infer_sectors.py 43
